import java.util.*;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
//import java packages to use SHA-256
public class cryptohash
 {
    public static String encryptThisString(String input)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) 
            {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) 
        {
            throw new RuntimeException(e);
        }
    }
//function generates hascode by SHA-256 for given string and returns hashcode in String format
    public static void main(String args[]) throws NoSuchAlgorithmException , InterruptedException
    {
           
        Scanner sc=new Scanner (System.in);
        System.out.println("Enter a String");
        String S=sc.nextLine();
        //String input taken from user
        long startTime = System.nanoTime();
        //timer starts here
        System.out.println("String you entered - "+S);
        String newS=encryptThisString(S);
        //stores hashcode of our entered string
        System.out.println("HashCode Generated by SHA-256 for entered String - " + newS);
            int len=newS.length();//length of hashcode
            String tempS="";
            String hashS="";
            for(int i=0;;i++)
            {
                tempS=S+String.valueOf(i);//here we are appending each number in form of String for checking
                hashS=encryptThisString(tempS);//after appending number, we are storing its hashcode here
                len=hashS.length();//length of new hashcode
                //our program does not consider leading zeroes in hashcode,so if hashcode has 5 zeroes in beginning they would not be considered
                //Using this advantage ,for our program , length of required hashcode is 64-5=59
                if(len==59) 
                {
                System.out.println("Magic Number - " +i);//got our required number
                break;//no need to check further so break
                }
        }
            System.out.println("Entered String appended with magic number - "+tempS);
            if(len<64)
            {
                for(int j=1;j<=(64-len);j++)
                {
                    hashS= "0"+hashS;
                 }
             }//appending extra zeroes at beginning
            System.out.println("HashCode Generated by SHA-256 for changed String - "+hashS);   
            long endTime = System.nanoTime();
             //timer ends
            long timeElapsed = endTime - startTime;//required time in nanoseconds
            System.out.println("Time taken to get this nonce value - " + (timeElapsed/1000000000.0)+" seconds. ");//printing time after converting in seconds      
    }
}
