import time # to calculate time taken for execution
import hashlib # to generate hahcode by sha-256
S = input("Enter a string ") # Enter a string by user
begin = time.time() # Timer begins here
result = hashlib.sha256(S.encode()) 
print("HashCode Generated by SHA-256 for", S, " is : ")
print(result.hexdigest()) # result generated
c = 0 # used as a flag
x = 0 # generates numbers
newResult = "" # empty String type variable 
while c == 0: 
    tempS = S + str(x) # generates new string by appending number
    newResult = hashlib.sha256(tempS.encode()) # hashcode generated for new string
    if newResult.hexdigest()[0:5] == "00000": # checks if first five characters are zero or not
        c = c + 1 # if yes, c  becomes 1 allowing while loop to finish 
    else:
        x = x + 1 # if no, checks for another number
print("Number", x) # printing of number that qualifies above check
print("Required HashCode Generated by SHA-256 for entered String -", newResult.hexdigest()) # printing required hashcode
end = time.time() # timer ends here
print(f"Total runtime of the program is {end - begin}") # prints time of execution
