import time
import hashlib
S = input(" Enter a string ")
begin = time.time()
result = hashlib.sha256(S.encode())
print(" The hexadecimal equivalent of ", S, " is : ")
print(result.hexdigest())
c = 0
x = 0
newResult = hashlib.sha256(S.encode())
while c == 0:
    tempS = S + str(x)
    newResult = hashlib.sha256(tempS.encode())
    if newResult.hexdigest()[0:5] == "00000":
        c = c + 1
    else:
        x = x + 1
print("Number", x)
print("Required HashCode Generated by SHA-256 for entered String -", newResult.hexdigest())
end = time.time()
print(f"Total runtime of the program is {end - begin}")
